import React, { useState } from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet, ActivityIndicator, RefreshControl, Alert } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useNavigation, useFocusEffect } from '@react-navigation/native';
import { colors } from '../../theme';
import { teamsService, Team } from '../../services/teams.service';
export function MyTeamsScreen() {
  const navigation = useNavigation();
  const [teams, setTeams] = useState<Team[]>([]); const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  useFocusEffect(React.useCallback(() => { loadMyTeams(); }, []));
  const loadMyTeams = async () => { try { const data = await teamsService.getMyTeams(); setTeams(data); } catch (error:any) { Alert.alert('Error', error.message); } finally { setLoading(false); setRefreshing(false); } };
  const handleRefresh = () => { setRefreshing(true); loadMyTeams(); };
  const renderTeamCard = ({ item }: { item: Team }) => (<TouchableOpacity style={styles.teamCard} onPress={() => navigation.navigate('TeamDetail' as never, { teamId: item.id } as never)}><View style={styles.teamIcon}><Text style={styles.teamInitial}>{item.short_name?.[0] || item.name[0]}</Text></View><View style={styles.teamInfo}><Text style={styles.teamName}>{item.name}</Text>{item.short_name && <Text style={styles.teamShortName}>{item.short_name}</Text>}</View><Feather name="chevron-right" size={20} color={colors.textMuted} /></TouchableOpacity>);
  if (loading) return (<View style={styles.container}><View style={styles.loadingContainer}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingText}>Loading your teams...</Text></View></View>);
  return (<View style={styles.container}><View style={styles.header}><View><Text style={styles.headerTitle}>My Teams</Text><Text style={styles.headerSub}>{teams.length} team{teams.length !== 1 ? 's' : ''}</Text></View><TouchableOpacity style={styles.addButton} onPress={() => navigation.navigate('CreateTeam' as never)}><Feather name="plus" size={20} color={colors.textInverse} /></TouchableOpacity></View><FlatList data={teams} renderItem={renderTeamCard} keyExtractor={(item)=>item.id} contentContainerStyle={styles.listContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} tintColor={colors.primary} />} ListEmptyComponent={<View style={styles.emptyContainer}><View style={styles.emptyIconWrap}><Feather name="users" size={40} color={colors.textMuted} /></View><Text style={styles.emptyTitle}>No teams yet</Text><Text style={styles.emptyText}>Create or join a team to get started on your cricket journey.</Text><TouchableOpacity style={styles.createButton} onPress={() => navigation.navigate('CreateTeam' as never)}><Feather name="plus" size={18} color={colors.textInverse} /><Text style={styles.createButtonText}>Create Team</Text></TouchableOpacity></View>} /></View>);
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},loadingContainer:{flex:1,justifyContent:'center',alignItems:'center'},loadingText:{marginTop:14,fontSize:15,color:colors.textSecondary},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:20,paddingTop:18,paddingBottom:14},headerTitle:{fontSize:26,fontWeight:'800',color:colors.textPrimary},headerSub:{fontSize:13,color:colors.textSecondary,marginTop:2},addButton:{width:42,height:42,borderRadius:21,backgroundColor:colors.primary,justifyContent:'center',alignItems:'center',shadowColor:colors.primary,shadowOffset:{width:0,height:4},shadowOpacity:0.3,shadowRadius:10,elevation:6},listContent:{paddingHorizontal:16,paddingBottom:24},teamCard:{flexDirection:'row',alignItems:'center',backgroundColor:colors.backgroundCard,padding:16,borderRadius:16,marginBottom:10,borderWidth:1,borderColor:colors.border},teamIcon:{width:52,height:52,borderRadius:16,backgroundColor:colors.primaryMuted,justifyContent:'center',alignItems:'center',marginRight:14,borderWidth:1,borderColor:'rgba(0,255,102,0.15)'},teamInitial:{fontSize:20,fontWeight:'800',color:colors.primary},teamInfo:{flex:1},teamName:{fontSize:16,fontWeight:'700',color:colors.textPrimary,marginBottom:3},teamShortName:{fontSize:13,fontWeight:'600',color:colors.primary},emptyContainer:{alignItems:'center',paddingVertical:64,paddingHorizontal:20},emptyIconWrap:{width:80,height:80,borderRadius:40,backgroundColor:colors.backgroundCard,justifyContent:'center',alignItems:'center',marginBottom:20,borderWidth:1,borderColor:colors.border},emptyTitle:{fontSize:20,fontWeight:'700',color:colors.textPrimary,marginBottom:8},emptyText:{fontSize:14,color:colors.textSecondary,textAlign:'center',marginBottom:24,lineHeight:20},createButton:{flexDirection:'row',backgroundColor:colors.primary,paddingHorizontal:22,paddingVertical:13,borderRadius:14,gap:8,alignItems:'center'},createButtonText:{fontSize:15,fontWeight:'700',color:colors.textInverse}});