/**
 * CreateScreen — Premium Dark UI
 */
import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Alert } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
interface CreateOption { id:string; title:string; subtitle:string; icon:keyof typeof Feather.glyphMap; color:string; screen?:string; comingSoon?:boolean; }
const OPTIONS:CreateOption[]=[{id:'match',title:'Create Match',subtitle:'Set up a cricket match with teams',icon:'zap',color:colors.primary,screen:'CreateMatch'},{id:'team',title:'Create Team',subtitle:'Build your own cricket team',icon:'users',color:colors.accent.blue,screen:'CreateTeam'},{id:'tournament',title:'Create Tournament',subtitle:'Organize a full tournament',icon:'award',color:colors.accent.orange,screen:'CreateTournament'},{id:'event',title:'Create Event',subtitle:'Plan a practice or event',icon:'calendar',color:colors.accent.purple,comingSoon:true},{id:'post',title:'Create Post',subtitle:'Share moments with the community',icon:'edit-3',color:'#FF6B8A',comingSoon:true},{id:'play',title:'Play Now',subtitle:'Quickly find or join a game',icon:'play-circle',color:colors.accent.red,screen:'Matches'}];
export default function CreateScreen({ navigation }: any) {
  const handlePress=(opt:CreateOption)=>{if(opt.comingSoon){Alert.alert('Coming Soon',`${opt.title} will be available in the next update.`);return;}if(opt.screen)navigation.navigate(opt.screen);};
  return (<View style={styles.container}><View style={styles.header}><View style={styles.headerLeft}><View style={styles.logoCircle}><Feather name="plus-circle" size={22} color={colors.primary}/></View><Text style={styles.headerTitle}>Create</Text></View><Text style={styles.headerSub}>Build, organize, and play</Text></View><ScrollView style={styles.content} showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}><Text style={styles.tagline}>What would you like to create?</Text><View style={styles.cardGrid}>{OPTIONS.map((opt)=>(<TouchableOpacity key={opt.id} style={[styles.card,opt.id==='play'&&styles.playCard]} onPress={()=>handlePress(opt)} activeOpacity={0.82}><View style={[styles.cardIcon,{backgroundColor:`${opt.color}15`}]}><Feather name={opt.icon} size={22} color={opt.color}/></View><View style={styles.cardBody}><View style={styles.cardTitleRow}><Text style={styles.cardTitle}>{opt.title}</Text>{opt.comingSoon&&(<View style={styles.comingSoonBadge}><Text style={styles.comingSoonText}>Soon</Text></View>)}</View><Text style={styles.cardSub}>{opt.subtitle}</Text></View><Feather name="chevron-right" size={18} color={colors.textMuted}/></TouchableOpacity>))}</View></ScrollView></View>);
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{paddingHorizontal:20,paddingTop:16,paddingBottom:18,borderBottomWidth:1,borderBottomColor:colors.divider},headerLeft:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:6},logoCircle:{width:34,height:34,borderRadius:17,borderWidth:1.5,borderColor:colors.primary,alignItems:'center',justifyContent:'center',backgroundColor:colors.primaryMuted},headerTitle:{fontSize:22,fontWeight:'800',color:colors.textPrimary},headerSub:{fontSize:13,color:colors.textSecondary,marginLeft:44},content:{flex:1},scrollContent:{paddingHorizontal:20,paddingTop:24,paddingBottom:40},tagline:{fontSize:20,fontWeight:'700',color:colors.textPrimary,marginBottom:20},cardGrid:{gap:12},card:{flexDirection:'row',alignItems:'center',backgroundColor:colors.backgroundCard,borderRadius:18,padding:18,borderWidth:1,borderColor:colors.border,gap:14},playCard:{borderColor:colors.primary,borderWidth:1.5,backgroundColor:colors.primaryMuted},cardIcon:{width:50,height:50,borderRadius:16,alignItems:'center',justifyContent:'center'},cardBody:{flex:1},cardTitleRow:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:4},cardTitle:{fontSize:16,fontWeight:'700',color:colors.textPrimary},comingSoonBadge:{paddingHorizontal:8,paddingVertical:3,borderRadius:8,backgroundColor:'rgba(255,255,255,0.08)'},comingSoonText:{fontSize:10,fontWeight:'600',color:colors.textMuted},cardSub:{fontSize:13,color:colors.textSecondary}});